### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Scorpio-y** [mkoz71/Energy-Efficiency-in-Reinforcement-Learning#1]
Where can I find your published paper? Could you please provide the link of the paper? thank you!!!

**Comment by mkoz71** [comment]
Hi, 

You can find the paper on arxiv:

https://arxiv.org/pdf/1812.02538.pdf

Thanks

**Comment by Scorpio-y** [comment]
Thanks for your reply! I thought it was on IEEE. 😊
